### ISSUE TITLE
ICS-Parser

### ISSUE THREAD

**Issue by 205er** [ffbsee/static_startpage#4]
Wir benötigen einen ICS-Parser, der die nächsten Termine aus dem FF-Kalender zieht und auf der Startseite ausgibt.

**Comment by 205er** [comment]
@DO1JLR: *haha* lass uns bei Gelegenheit mal darüber sprechen.

**Comment by DO1JLR** [comment]
Wie wäre es, wenn wir das heute mal in der Toolbox angehen?
Ich zeig dir, wie ich das mit dem RSS Parser gemacht habe und du hast ne bessere und elegantere Idee das für ICS umzusetzen!

**Comment by 205er** [comment]
Ideen und/oder Vorschläge, wie man die Events am besten ausgeben sollte?
Mein Plan ist, die nächsten drei Termine anzuzeigen. Dabei jedoch nur Datum & Kurztext anzuzeigen und ggf. per Mouse over weitere Infos anzuzeigen...

**Comment by DO1JLR** [comment]
Mich würde dabei nicht nur das Datum und die Beschreibung interessieren, sondern auch die Startzeit und den Ort.

Aktuell steht auf unserer Webseite: 
`Freifunk Community-Treffen 13. September 2017, 19 Uhr in der Toolbox Markdorf.`

Eigendlich wäre genau das ganz gut, zusammen mit einer kleinen Beschreibung die zB. in einer kleineren font noch ein paar Informationen zum Event liefert.

**Comment by DO1JLR** [comment]
@205er Oder was meinst du so...

**Comment by DO1JLR** [comment]
Erledigt:
6103d0d4d96459b2b226d429de51237a67f27013

**Comment by 205er** [comment]
Dann werfe ich meine (fast fertige) Lösung halt weg!

**Comment by DO1JLR** [comment]
Nein, bitte nicht.

Meins ist nur eine Frickellösung die nur halb-gut funktioniert und bei der ich den Verdacht habe, dass sie mit Sonderzeichen wie "ä", "ß" und "é" Probleme hat.

**Comment by 205er** [comment]
Ok, dann mach ich meinen Parser halt noch fertig. ;)

**Comment by 205er** [comment]
Ich zeige dir morgen mal, was ich gemacht habe. Dann können wir es auch gern zusammen testen und ggf. direkt live setzen.
