### ISSUE TITLE
"Link zum Artikel" fehlerhaft

### ISSUE THREAD

**Issue by 205er** [ffbsee/static_startpage#5]
Moin,

der "Link zum Artikel", den man unter jedem News-Eintrag findet, führt nur bei ersten Eintrag ans korrekte Ziel. Die anderen beiden Links zeigen entweder auf den falschen Eintrag oder sind nicht klickbar (weil der HTML-Code für die Verlinkung fehlerhaft ist).

**Comment by DO1JLR** [comment]
https://github.com/ffbsee/static_startpage/commit/64a00e3f19c083c67439d178f96fd37fa0d5c871
