### ISSUE TITLE
Bilder auf der Startseite werden nicht angezeigt

### ISSUE THREAD

**Issue by 205er** [ffbsee/static_startpage#6]
Bilder auf der Startseite werden nicht angezeigt. Betroffen sind ausschließlich Grafiken, die über das Wiki abgerufen werden.

**Comment by mart-ffbsee** [comment]
immer noch das gleiche Problem. das durch restart von apache behoben werden kann

**Comment by mart-ffbsee** [comment]
bzw. gerade wurde

**Comment by 205er** [comment]
Perfekt! Danke mart!
